# Starter pipeline
- task: Security static source code analysis@2019
  inputs:
    CheckmarxService: 'Checkmarx 10.32.3.14'
    projectName: 'Check Azure DevOps'
    preset: 'Checkmarx Default'
    incScan: true
- task: Security static source code analysis@2019
  inputs:
    preset: 'Checkmarx Default'
    incScan: true
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Security static source code analysis@2019
  inputs:
    CheckmarxService: 'Checkmarx 10.32.3.14'
    projectName: 'shiranCheck.Admin3050_new'
    preset: 'Checkmarx Default'
    fullTeamName: 'CxServer'
    incScan: false
    vulnerabilityThreshold: false
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
